config/routes.rb
Rails.application.routes.draw do
  resources :players, :items, :clans

  root 'players#index'
  get 'index' => 'players#index'
  get 'ranks' => 'players#ranks'
  get 'ehp' => 'players#ehp'
  get 'fake' => 'players#fake'
  get 'possible_fakes' => 'players#possible_fakes'
  get 'links' => 'players#links'
  get 'changelog' => 'players#changelog'
  get 'oldchangelog' => 'players#oldchangelog'
  get 'donate' => 'players#donate'
  get 'controls' => 'players#controls'
  get 'plaintext' => 'players#plaintext'
  get 'tracking_plaintext' => 'players#tracking_plaintext'
  get 'names' => 'players#names'
  get 'monster_ratio' => 'players#monster_ratio'
  get 'melee_order' => 'players#melee_order'
  get 'dps' => 'players#dps'
  get 'combat' => 'players#combat'
  get 'calcs' => 'players#calcs'
  get 'gpxp' => 'items#gpxp'
  get 'compare' => 'players#compare'
  get 'test' => 'players#test'
  get 'competitions' => 'players#competitions'
  get 'tracking' => 'players#tracking'
  get 'records' => 'players#records'
  get 'faqs' => 'players#faqs'
  get 'a_new_meta' => 'players#a_new_meta'
  get 'admin' => 'admin#index'
  put 'players.:id' => 'players#update_player'
  put 'update' => 'players#update_player'
  get 'players/:id/update' => 'players#update', as: :update_player
  get 'players/:id/check_acc_type' => 'players#check_acc_type', as: :check_acc_type
  get 'clans/index' => 'clans#index'
  get 'clans' => 'clans#index'
  get 'clans/:id/admin' => 'clans#admin', as: :clan_admin
  post 'clans/:id/add_player_to_clan' => 'clans#add_player_to_clan', as: :add_player_to_clan
  post 'clans/:id/add_many_players_to_clan' => 'clans#add_many_players_to_clan', as: :add_many_players_to_clan
  post 'clans/:id/remove_player_from_clan' => 'clans#remove_player_from_clan', as: :remove_player_from_clan
  post 'clans/:id/remove_many_players_from_clan' => 'clans#remove_many_players_from_clan', as: :remove_many_players_from_clan
  post 'clans/:id/update_clan_description' => 'clans#update_clan_description', as: :update_clan_description
  post 'clans/:id/update_clan_link1' => 'clans#update_clan_link1', as: :update_clan_link1
  post 'clans/:id/update_clan_link2' => 'clans#update_clan_link2', as: :update_clan_link2
  post 'players#index' => 'players#refresh_250', as: :refresh_250
  post 'players#index' => 'players#refresh_players', as: :refresh_players
  post 'players#secretpage' => 'players#export_players', as: :export_players
  post 'players#names' => 'players#find_new', as: :find_new
  post 'items#update_prices' => 'items#update_prices', as: :update_prices
  post 'items#create_items' => 'items#create_items', as: :create_items
  post 'admin#add_supporter' => 'admin#add_supporter', as: :add_supporter
  post 'admin#fix_spaces' => 'admin#fix_spaces', as: :fix_spaces
  post 'admin#change_name' => 'admin#change_name', as: :change_name

end

app/views/admin/index.html.haml
- @title = "Admin" 
= link_to image_tag("f2pwiki.png"), players_path

%p#notice= notice

= content_tag(:div, nil, class: "container", style: "width: 820px;") do 
  = content_tag(:div, nil, class: ["bar", "ranks"]) do
    = link_to "Hiscores", ranks_path
  = content_tag(:div, nil, class: ["bar", "fake"]) do 
    = link_to "Current Top", tracking_path
  = content_tag(:div, nil, class: ["bar", "ehp"]) do 
    = link_to "Records", records_path
  = content_tag(:div, nil, class: ["bar", "ehp"]) do 
    = link_to "EHP Rates", ehp_path
  = content_tag(:div, nil, class: ["bar", "links"]) do 
    = link_to "Links", links_path
  = content_tag(:div, nil, class: ["bar", "changelog"]) do 
    = link_to "Changelog", changelog_path
  = content_tag(:div, nil, class: ["bar", "donate"]) do 
    = link_to "About Us/Donate", donate_path

= content_tag(:div, nil, class: "container", style: "width: 820px;") do 
  = content_tag(:div, nil, class: ["container", "search"], style: "margin-left: 15px; width: 140px; height: 96px; display: inline-block;") do 
    = form_tag add_supporter_path, :method => "post", id: "add-supporter-form" do
      = "Add Supporter"
      %br
      = text_field_tag :player_supporter, params[:player_supporter], placeholder: "Player Name", :class => "add-player-field", style: "width: 100px;"
      %br
      = submit_tag "Add"
      
  = content_tag(:div, nil, class: ["container", "search"], style: "margin-left: 15px; width: 140px; height: 96px; display: inline-block;") do 
    = form_tag fix_spaces_path, :method => "post", id: "fix-spaces-form" do
      = "Fix Name Spaces"
      %br
      = text_field_tag :name_spaces, params[:name_spaces], placeholder: "Player Name", :class => "add-player-field", style: "width: 100px;"
      %br
      = submit_tag "Fix"

  = content_tag(:div, nil, class: ["container", "filter"], style: "margin-left: 15px; width: 140px; height: 126px; display: inline-block;") do 
    = form_tag change_name_path, :method => "post", id: "change-name-form" do
      = "Change Name"
      %br
      = text_field_tag :name1, params[:name1], placeholder: "Current name", :class => "search-field", style: "width: 100px;"
      %br
      = text_field_tag :name2, params[:name2], placeholder: "New name", :class => "search-field", style: "width: 100px;"
      %br
      = submit_tag "Change"