config/routes.rb
Rails.application.routes.draw do
  resources :players, :items, :clans

  root 'players#index'
  get 'index' => 'players#index'
  get 'ranks' => 'players#ranks'
  get 'ehp' => 'players#ehp'
  get 'fake' => 'players#fake'
  get 'possible_fakes' => 'players#possible_fakes'
  get 'links' => 'players#links'
  get 'changelog' => 'players#changelog'
  get 'oldchangelog' => 'players#oldchangelog'
  get 'donate' => 'players#donate'
  get 'controls' => 'players#controls'
  get 'plaintext' => 'players#plaintext'
  get 'tracking_plaintext' => 'players#tracking_plaintext'
  get 'names' => 'players#names'
  get 'monster_ratio' => 'players#monster_ratio'
  get 'melee_order' => 'players#melee_order'
  get 'dps' => 'players#dps'
  get 'combat' => 'players#combat'
  get 'calcs' => 'players#calcs'
  get 'gpxp' => 'items#gpxp'
  get 'compare' => 'players#compare'
  get 'test' => 'players#test'
  get 'competitions' => 'players#competitions'
  get 'tracking' => 'players#tracking'
  get 'records' => 'players#records'
  get 'faqs' => 'players#faqs'
  get 'a_new_meta' => 'players#a_new_meta'
  get 'admin' => 'admin#index'
  put 'players.:id' => 'players#update_player'
  put 'update' => 'players#update_player'
  get 'players/:id/update' => 'players#update', as: :update_player
  get 'players/:id/check_acc_type' => 'players#check_acc_type', as: :check_acc_type
  get 'clans/index' => 'clans#index'
  get 'clans' => 'clans#index'
  get 'clans/:id/admin' => 'clans#admin', as: :clan_admin
  post 'clans/:id/add_player_to_clan' => 'clans#add_player_to_clan', as: :add_player_to_clan
  post 'clans/:id/add_many_players_to_clan' => 'clans#add_many_players_to_clan', as: :add_many_players_to_clan
  post 'clans/:id/remove_player_from_clan' => 'clans#remove_player_from_clan', as: :remove_player_from_clan
  post 'clans/:id/remove_many_players_from_clan' => 'clans#remove_many_players_from_clan', as: :remove_many_players_from_clan
  post 'clans/:id/update_clan_description' => 'clans#update_clan_description', as: :update_clan_description
  post 'clans/:id/update_clan_link1' => 'clans#update_clan_link1', as: :update_clan_link1
  post 'clans/:id/update_clan_link2' => 'clans#update_clan_link2', as: :update_clan_link2
  post 'players#index' => 'players#refresh_250', as: :refresh_250
  post 'players#index' => 'players#refresh_players', as: :refresh_players
  post 'players#secretpage' => 'players#export_players', as: :export_players
  post 'players#names' => 'players#find_new', as: :find_new
  post 'items#update_prices' => 'items#update_prices', as: :update_prices
  post 'items#create_items' => 'items#create_items', as: :create_items
  post 'admin#add_supporter' => 'admin#add_supporter', as: :add_supporter
  post 'admin#fix_spaces' => 'admin#fix_spaces', as: :fix_spaces
  post 'admin#change_name' => 'admin#change_name', as: :change_name

end

app/models/clan.rb
class Clan < ActiveRecord::Base
  # This model intentionally does not have a way of conveniently adding records.
  # Due to the Heroku 10000 row limit, we need to limit the number of clans, players, and clan links.
  # In order to create a new clan, run the following in the Rails console:
  #    `Clan.create!({:name => "Some Clan", :symbol_link => "some_clan.png", :pass => Digest::MD5.hexdigest("mypassword")})`

  has_many :player_clan_links
  has_many :players, through: :player_clan_links

  def self.sanitize_name(str)
    str = ERB::Util.url_encode(str).gsub(/[-_\\+]|(%20)|(%C2%A0)/, " ")
    return str.gsub(/\A[^A-z0-9]+|[^A-z0-9\s\_-]+|[^A-z0-9]+\z/, "")
  end

  def self.find_clan(id)
    id = self.sanitize_name(id)
    splits = id.split(/[\s\_]|(%20)/)
    res = splits.join("_") # _ is a wildcard
    clan = Clan.where("lower(name) like '%#{res.downcase}%' and length(name) = length('#{res.downcase}')").first

    if clan.nil?
      begin
        clan = Clan.find(Float(id))
      rescue
        return false
      end
    end
    return clan
  end

  def add_player(player)
    PlayerClanLink.create({:player_id => player.id, :clan_id => self.id})
  end

  def remove_player(player)
    PlayerClanLink.where("player_id = #{player.id} and clan_id = #{self.id}").destroy_all
  end
end

app/controllers/clans_controller.rb
require 'net/https'
require 'uri'
require "open-uri"
require 'nokogiri'
require 'will_paginate/array'

class ClansController < ApplicationController
  before_action :set_clan, only: %i[show edit update destroy]

  def admin
    @clan = params[:id]
  end

  def add_player_to_clan
    clan_name = params[:id]
    clan = Clan.find_clan(clan_name)
    clan_id = clan.id

    player = Player.find_player(params[:player_name])

    if clan.pass != Digest::MD5.hexdigest(params[:pass])
      redirect_to(clan_admin_path, notice: "Incorrect password. Please try again.")
    elsif player and clan.players.pluck(:player_id).include?(player.id)
      redirect_to clan_admin_path, notice: "#{player.player_name} is already in #{clan_name.gsub("_", " ")}."
    elsif player
      clan.add_player(player)
      redirect_to clan_admin_path, notice: "#{player.player_name} added to #{clan_name.gsub("_", " ")}."
    else
      redirect_to clan_admin_path, notice: "Could not find player #{params[:player_name]}."
    end
  end

  def add_many_players_to_clan
    clan_name = params[:id]
    clan = Clan.find_clan(clan_name)
    clan_id = clan.id

    updated_players = []
    failed_players = []
    redundant_players = []

    player_names = params[:player_names].split(",")
    if clan.pass != Digest::MD5.hexdigest(params[:pass])
      redirect_to(clan_admin_path, notice: "Incorrect password. Please try again.")
      return
    elsif player_names.size > 100
      redirect_to(clan_admin_path, notice: "Too many players. Please try again with fewer than 100 players.")
      return
    end

    player_names.each do |player_name|
      player = Player.find_player(player_name)
      if player and clan.players.pluck(:player_id).include?(player.id)
        redundant_players += [player.player_name]
      elsif player
        clan.add_player(player)
        updated_players += [player.player_name]
      else
        failed_players += [player_name]
      end
    end

    notice_msg =  "Players added to #{clan_name.gsub("_", " ")}: #{updated_players}"
    notice_msg += "\nPlayers not found: #{failed_players}"
    notice_msg += "\nPlayers already in #{clan_name.gsub("_", " ")}: #{redundant_players}"

    redirect_to clan_admin_path, notice: notice_msg
  end

  def remove_player_from_clan
    clan_name = params[:id]
    clan = Clan.find_clan(clan_name)
    clan_id = clan.id

    player = Player.find_player(params[:player_name])

    if clan.pass != Digest::MD5.hexdigest(params[:pass])
      redirect_to(clan_admin_path, notice: "Incorrect password. Please try again.")
    elsif player and clan.players.pluck(:player_id).include?(player.id)
      clan.remove_player(player)
      redirect_to clan_admin_path, notice: "#{player.player_name} removed from #{clan_name.gsub("_", " ")}."
    else
      redirect_to clan_admin_path, notice: "Player #{params[:player_name]} not found, or not in #{clan_name.gsub("_", " ")}."
    end
  end

  def remove_many_players_from_clan
    clan_name = params[:id]
    clan = Clan.find_clan(clan_name)
    clan_id = clan.id

    updated_players = []
    failed_players = []

    player_names = params[:player_names].split(",")
    if clan.pass != Digest::MD5.hexdigest(params[:pass])
      redirect_to(clan_admin_path, notice: "Incorrect password. Please try again.")
      return
    elsif player_names.size > 100
      redirect_to(clan_admin_path, notice: "Too many players. Please try again with fewer than 100 players.")
      return
    end

    player_names.each do |player_name|
      player = Player.find_player(player_name)
      if player and clan.players.pluck(:player_id).include?(player.id)
        clan.remove_player(player)
        updated_players += [player.player_name]
      else
        failed_players += [player_name]
      end
    end

    notice_msg =  "Players been removed from #{clan_name.gsub("_", " ")}: #{updated_players}"
    notice_msg += "\nPlayers not found, or are not in the clan: #{failed_players}"

    redirect_to clan_admin_path, notice: notice_msg
  end

  def set_default_description
    @default_description = 'F2P.wiki is an open source Old School RuneScape hiscores for Free-to-play players. It also includes EHP tracking, information about meta changes, and various F2P Old School RuneScape tools.'
  end
  before_action :set_default_description

  def index
    @clans = Clan.all
  end

  def show
    id = params[:search] || params[:id]
    @clan = Clan.find_clan(id)

    if not @clan
      redirect_to clans_path, notice: "Clan '#{id}' not found."
      return
    end

    @display = params[:display] || session[:display] || "stats"
    @time = params[:time] || session[:time] || "week"

    if params[:display] != session[:display] || params[:time] != session[:time]
      session[:display] = @display
      session[:time] = @time
    end

    @sort_by = params[:sort_by] || session[:sort_by] || {}
    @skill = params[:skill] || session[:skill] || {}
    @filter_inactive = params[:filter_inactive] || session[:filter_inactive] || "false"
    @clear_filters = params[:clear_filters]

    if @clear_filters
      @sort_by = {}
      @skill = {}
      @filter_inactive = "false"
    end

    if @skill == {}
      @skill = "overall"
      params[:skill] = "overall"
      session[:skill] = "overall"
    end

    @display = params[:display] || session[:display] || "stats"
    @time = params[:time] || session[:time] || "week"

    if params[:display] != session[:display] || params[:time] != session[:time] || params[:filter_inactive] != session[:filter_inactive]
      session[:display] = @display
      session[:time] = @time
      session[:filter_inactive] = @filter_inactive
    end

    case @time
    when "day"
      @time_display = Time.now.gmtime.strftime("%b %d, %Y")
    when "week"
      @time_display = Time.now.gmtime.beginning_of_week.strftime("%b %d, %Y")
    when "month"
      @time_display = Time.now.gmtime.strftime("%b %Y")
    when "year"
      @time_display = Time.now.gmtime.year
    end

    if params[:sort_by] != session[:sort_by] || params[:skill] != session[:skill]
      session[:skill] = @skill
      session[:sort_by] = @sort_by
    end

    # Sort some skills by xp not ehp as ehp is mostly 0
    @skills_by_xp = ['magic', 'mining']
    if @sort_by == {} && @skills_by_xp.include?(@skill)
      @sort_by = "xp"
    elsif @sort_by == {}
      @sort_by = "ehp"
    end

    if @display == "stats"
      if @skill.include?("ttm")
        case @skill
        when "ttm_lvl"
          ordering = "ttm_lvl ASC, overall_ehp DESC"
        when "ttm_xp"
          ordering = "ttm_xp ASC, overall_ehp DESC"
        end
      elsif @skill.include?("clues")
        case @skill
        # when "clues_all"
          # ordering = "clues_all DESC, players.id ASC"
        when "clues_beginner"
          ordering = "clues_beginner DESC, players.id ASC"
        end
      elsif @skill.include?("no_combats")
        ordering = "overall_ehp DESC"
      elsif @skill.include?("count")
        ordering = "overall_ehp DESC"
      elsif @skill.include?("lowest_lvl")
        ordering = "overall_ehp DESC"
      elsif @skill.include?("lms")
        ordering = "lms_score DESC, lms_rank ASC"
      elsif @skill.include?("_kc")
        ordering = "#{@skill} DESC, #{@skill}_rank ASC"
      else
        case @sort_by
        when "ehp"
          @player_ehp_header = 'hilite'
          ordering = "#{@skill}_ehp DESC, #{@skill}_lvl DESC, #{@skill}_xp DESC, #{@skill}_rank ASC, players.id ASC"
        when "lvl"
          @player_lvl_header = 'hilite'
          if @skill == "combat"
            ordering = "#{@skill}_lvl DESC, overall_ehp DESC"
          else
            ordering = "#{@skill}_lvl DESC, #{@skill}_xp DESC, #{@skill}_rank ASC"
          end
        when "xp"
          @player_xp_header = 'hilite'
          ordering = "#{@skill}_xp DESC, #{@skill}_rank ASC"
        end
      end
    elsif @display == "gains"
      unless F2POSRSRanks::Application.config.f2p_skills.include?(@skill)
        @skill = "overall"
        params[:skill] = "overall"
        session[:skill] = "overall"
      end

      case @sort_by
      when "ehp", "lvl"
        @sort_by = "ehp"
        @player_ehp_header = 'hilite'
        ordering = "#{@skill}_ehp - COALESCE(#{@skill}_ehp_#{@time}_start, 100000) DESC, #{@skill}_xp - COALESCE(#{@skill}_xp_#{@time}_start, 1000000000) DESC, #{@skill}_ehp DESC, #{@skill}_xp DESC, players.id ASC"
      when "xp"
        @player_xp_header = 'hilite'
        ordering = "#{@skill}_xp - COALESCE(#{@skill}_xp_#{@time}_start, 1000000000) DESC, #{@skill}_ehp - COALESCE(#{@skill}_ehp_#{@time}_start, 100000) DESC, #{@skill}_xp DESC"
      end
    elsif @display == "records"
      unless F2POSRSRanks::Application.config.f2p_skills.include?(@skill)
        @skill = "overall"
        params[:skill] = "overall"
        session[:skill] = "overall"
      end

      case @sort_by
      when "ehp", "lvl"
        @sort_by = "ehp"
        @player_ehp_header = 'hilite'
        ordering = "COALESCE(#{@skill}_ehp_#{@time}_max, -100000) DESC, COALESCE(#{@skill}_xp_#{@time}_max, -1000000000) DESC, #{@skill}_ehp DESC, #{@skill}_xp DESC, players.id ASC"
      when "xp"
        @player_xp_header = 'hilite'
        ordering = "COALESCE(#{@skill}_xp_#{@time}_max, -1000000000) DESC, COALESCE(#{@skill}_ehp_#{@time}_max, -100000) DESC, #{@skill}_xp DESC"
      end
    end

    if @sort_by == "player_name"
      ordering = "player_name ASC"
    end

    @players = @clan.players.where("potential_p2p <= 0")

    if @filter_inactive == "true"
      @players = @players.where("(overall_xp - overall_xp_month_start) > 0")
    end

    if @skill.include?("ttm")
      @players = @players.where("ttm_lvl != 0 or ttm_xp != 0 or overall_ehp > 1000")
    end
    if @skill == "combat"
      @players = @players.where("combat_lvl IS NOT NULL")
    end
    if @skill.include?("99_count")
      @players = @players.sort_by {|player| [player.count_99, player.overall_ehp] }.reverse

app/views/clans/_header.html.haml
%p#notice= notice

= content_tag(:div, nil, class: "container", style: "width: 840px;") do
  = content_tag(:div, nil, class: ["bar", "ranks", "selected-link"]) do
    = link_to_unless_current "Hiscores", ranks_path
  = content_tag(:div, nil, class: ["bar", "fake", "selected-link"]) do
    = link_to_unless_current "Current", tracking_path
  = content_tag(:div, nil, class: ["bar", "ehp", "selected-link"]) do
    = link_to_unless_current "Records", records_path
  = content_tag(:div, nil, class: ["bar", "ehp", "selected-link"]) do
    = link_to_unless_current "EHP", ehp_path
  = content_tag(:div, nil, class: ["bar", "links", "selected-link"]) do
    = link_to_unless_current "Clans", clans_path
  = content_tag(:div, nil, class: ["bar", "links", "selected-link"]) do
    = link_to_unless_current "Links", links_path
  = content_tag(:div, nil, class: ["bar", "changelog", "selected-link"]) do
    = link_to_unless_current "Changelog", changelog_path
  = content_tag(:div, nil, class: ["bar", "donate", "selected-link"]) do
    = link_to_unless_current "About Us/Donate", donate_path
  = content_tag(:div, nil, class: ["bar", "faqs", "selected-link"]) do
    = link_to_unless_current "FAQs", faqs_path

app/views/clans/admin.html.haml
- @title = "#{@clan.gsub("_", " ")} Admin" 
= link_to image_tag("f2pwiki.png"), players_path

= render :partial => "header.html.haml",  :locals => {notice: notice}

= "#{@clan.gsub("_", " ")} Admin Page"
%br
= link_to "Back to Clan Page", clan_path
%br
%br

= content_tag(:div, nil, class: "container", style: "width: 820px;") do
  = content_tag(:div, nil, class: "left", style: "width: 420px; margin-left: 5px; padding: 10px;") do
    %h3 Update Players
    = content_tag(:div, nil, class: "container", style: "width: 420px;") do
      = content_tag(:div, nil, class: ["container", "filter"], style: "margin-left: 15px; width: 140px; height: 146px; display: inline-block;") do
        = form_tag add_player_to_clan_path, :method => "post", id: "update-clan-form" do
          = "Add to Clan"
          %br
          = text_field_tag :player_name, params[:player_name], placeholder: "Player Name", :class => "search-field", style: "width: 100px;"
          %br
          = password_field_tag :pass, params[:pass], placeholder: "Clan Password", :class => "search-field", style: "width: 100px;"
          %br
          = submit_tag "Add"

      = content_tag(:div, nil, class: ["container"], style: "margin-left: 15px; width: 240px; height: 186px; display: inline-block;") do
        = form_tag add_many_players_to_clan_path, :method => "post", id: "update-many-clans-form" do
          %br
          = "Add Multiple Players"
          %br
          = text_area_tag :player_names, params[:player_names], placeholder: "up to 100 comma separated names", :class => "search-field", style: "width: 180px; height: 100px;"
          %br
          = password_field_tag :pass, params[:pass], placeholder: "Clan Password", :class => "search-field", style: "width: 100px;"
          %br
          = submit_tag "Add"

    = content_tag(:div, nil, class: "container", style: "width: 420px;") do

      = content_tag(:div, nil, class: ["container", "filter"], style: "margin-left: 15px; width: 140px; height: 146px; display: inline-block;") do
        = form_tag remove_player_from_clan_path, :method => "post", id: "update-clan-form" do
          = "Remove from Clan"
          %br
          = text_field_tag :player_name, params[:player_name], placeholder: "Player Name", :class => "search-field", style: "width: 100px;"
          %br
          = password_field_tag :pass, params[:pass], placeholder: "Clan Password", :class => "search-field", style: "width: 100px;"
          %br
          = submit_tag "Remove"

      = content_tag(:div, nil, class: ["container"], style: "margin-left: 15px; width: 240px; height: 186px; display: inline-block;") do
        = form_tag remove_many_players_from_clan_path, :method => "post", id: "update-many-clans-form" do
          %br
          = "Remove Multiple Players"
          %br
          = text_area_tag :player_names, params[:player_names], placeholder: "up to 100 comma separated names", :class => "search-field", style: "width: 180px; height: 100px;"
          %br
          = password_field_tag :pass, params[:pass], placeholder: "Clan Password", :class => "search-field", style: "width: 100px;"
          %br
          = submit_tag "Remove"


  = content_tag(:div, nil, class: "left", style: "width: 280px; margin-left: 25px; padding: 10px;") do
    %h3 Update Clan Info
    = content_tag(:div, nil, class: ["container", "left"], style: "margin-left: 15px; width: 240px; height: 186px; display: inline-block;") do
      = form_tag update_clan_description_path, :method => "post", id: "update-clan-description-form" do
        %br
        = "Update Clan Description"
        %br
        = text_area_tag :clan_description, params[:clan_description], placeholder: "Clan Description (1000 characters or less)", :class => "search-field", style: "width: 180px; height: 100px;", size: "100"
        %br
        = password_field_tag :pass, params[:pass], placeholder: "Clan Password", :class => "search-field", style: "width: 100px;"
        %br
        = submit_tag "Add"

    = content_tag(:div, nil, class: ["container", "left"], style: "margin-left: 15px; width: 240px; height: 126px; display: inline-block;") do
      = form_tag update_clan_link1_path, :method => "post", id: "update-clan-link1-form" do
        %br
        = "Update Clan Link 1"
        = text_field_tag :link1, params[:link1], placeholder: "Link URL, ex: reddit.com/r/clan", :class => "search-field", style: "width: 180px"
        %br
        = text_field_tag :link1_name, params[:link1_name], placeholder: "Link label, ex: Reddit", :class => "search-field", style: "width: 180px"
        %br
        = password_field_tag :pass, params[:pass], placeholder: "Clan Password", :class => "search-field", style: "width: 100px;"
        %br
        = submit_tag "Update"

    = content_tag(:div, nil, class: ["container", "left"], style: "margin-left: 15px; width: 240px; height: 186px; display: inline-block;") do
      = form_tag update_clan_link2_path, :method => "post", id: "update-clan-link1-form" do
        %br
        = "Update Clan Link 2"
        = text_field_tag :link1, params[:link1], placeholder: "Link URL, ex: discord.gg/abcd", :class => "search-field", style: "width: 180px"
        %br
        = text_field_tag :link1_name, params[:link1_name], placeholder: "Link label, ex: Discord", :class => "search-field", style: "width: 180px"
        %br
        = password_field_tag :pass, params[:pass], placeholder: "Clan Password", :class => "search-field", style: "width: 100px;"
        %br
        = submit_tag "Update"

app/views/clans/index.html.haml
- @title = "Hiscores" 
= link_to image_tag("f2pwiki.png"), players_path

= render :partial => "header.html.haml",  :locals => {notice: notice}
= content_tag(:div, nil, class: "container", style: "width: 650px;") do 
  = content_tag(:div, nil, class: ["container", "left"], style: "width: 630px; max-width: 630px; overflow-x: auto; margin-top: 5px;") do

    = "Want to add your clan? Contact us at"
    = link_to "f2posrsranks@gmail.com", "mailto:f2posrsranks@gmail.com"

    = content_tag(:div, nil, class: "container", id: "headerHiscores", style: "margin: auto; margin-bottom: 0px; width: 630px; height: 60px;") 
    = content_tag(:table, nil, style: "text-align: center; width: 630px; padding: 4px; margin-bottom: 0px;") do 
      %thead
        %tr
          %th{:align => "center", :colspan => 10}
            = "F2P Clans"
      %thead
        %tr
          %th
          %th{:align => "left"} Name
          %th{:align => "left"} # Members
          %th{:align => "left"} Total XP
          %th{:align => "left"} Total EHP
          %th{:align => "left"} Average XP
          %th{:align => "left"} Average EHP
  
      %tbody
        - Clan.all.each do |clan|
          %tr
            - player_count = clan.players.count
            - sum_xp = clan.players.pluck(:overall_xp).sum
            - sum_ehp = clan.players.pluck(:overall_ehp).sum
            - avg_xp = player_count == 0 ? 0 : sum_xp/player_count
            - avg_ehp = player_count == 0 ? 0 : sum_ehp/player_count
            %td= image_tag clan.symbol_link, size: "35x35"
            %td{:align => "left"}= link_to clan.name, clan_path("#{clan.name.gsub(" ", "_")}")
            %td{:align => "left"}= clan.players.count
            %td{:align => "left"}= number_with_delimiter(sum_xp, :delimiter => ",", :separator => ".")
            %td{:align => "left"}= number_with_delimiter(number_with_precision(sum_ehp, :precision => 2), :delimiter => ",", :separator => ".")
            %td{:align => "left"}= number_with_delimiter(number_with_precision(avg_xp, :precision => 0), :delimiter => ",", :separator => ".")
            %td{:align => "left"}= number_with_delimiter(number_with_precision(avg_ehp, :precision => 2), :delimiter => ",", :separator => ".")
            
    = content_tag(:div, nil, class: "container", id: "footerHiscores", style: "margin: auto; margin-top: 0px; width: 630px; height: 61px;")