config/routes.rb
Rails.application.routes.draw do
  resources :players, :items, :clans

  root 'players#index'
  get 'index' => 'players#index'
  get 'ranks' => 'players#ranks'
  get 'ehp' => 'players#ehp'
  get 'fake' => 'players#fake'
  get 'possible_fakes' => 'players#possible_fakes'
  get 'links' => 'players#links'
  get 'changelog' => 'players#changelog'
  get 'oldchangelog' => 'players#oldchangelog'
  get 'donate' => 'players#donate'
  get 'controls' => 'players#controls'
  get 'plaintext' => 'players#plaintext'
  get 'tracking_plaintext' => 'players#tracking_plaintext'
  get 'names' => 'players#names'
  get 'monster_ratio' => 'players#monster_ratio'
  get 'melee_order' => 'players#melee_order'
  get 'dps' => 'players#dps'
  get 'combat' => 'players#combat'
  get 'calcs' => 'players#calcs'
  get 'gpxp' => 'items#gpxp'
  get 'compare' => 'players#compare'
  get 'test' => 'players#test'
  get 'competitions' => 'players#competitions'
  get 'tracking' => 'players#tracking'
  get 'records' => 'players#records'
  get 'faqs' => 'players#faqs'
  get 'a_new_meta' => 'players#a_new_meta'
  get 'admin' => 'admin#index'
  put 'players.:id' => 'players#update_player'
  put 'update' => 'players#update_player'
  get 'players/:id/update' => 'players#update', as: :update_player
  get 'players/:id/check_acc_type' => 'players#check_acc_type', as: :check_acc_type
  get 'clans/index' => 'clans#index'
  get 'clans' => 'clans#index'
  get 'clans/:id/admin' => 'clans#admin', as: :clan_admin
  post 'clans/:id/add_player_to_clan' => 'clans#add_player_to_clan', as: :add_player_to_clan
  post 'clans/:id/add_many_players_to_clan' => 'clans#add_many_players_to_clan', as: :add_many_players_to_clan
  post 'clans/:id/remove_player_from_clan' => 'clans#remove_player_from_clan', as: :remove_player_from_clan
  post 'clans/:id/remove_many_players_from_clan' => 'clans#remove_many_players_from_clan', as: :remove_many_players_from_clan
  post 'clans/:id/update_clan_description' => 'clans#update_clan_description', as: :update_clan_description
  post 'clans/:id/update_clan_link1' => 'clans#update_clan_link1', as: :update_clan_link1
  post 'clans/:id/update_clan_link2' => 'clans#update_clan_link2', as: :update_clan_link2
  post 'players#index' => 'players#refresh_250', as: :refresh_250
  post 'players#index' => 'players#refresh_players', as: :refresh_players
  post 'players#secretpage' => 'players#export_players', as: :export_players
  post 'players#names' => 'players#find_new', as: :find_new
  post 'items#update_prices' => 'items#update_prices', as: :update_prices
  post 'items#create_items' => 'items#create_items', as: :create_items
  post 'admin#add_supporter' => 'admin#add_supporter', as: :add_supporter
  post 'admin#fix_spaces' => 'admin#fix_spaces', as: :fix_spaces
  post 'admin#change_name' => 'admin#change_name', as: :change_name

end

app/controllers/players_controller.rb
require 'net/https'
require 'uri'
require "open-uri"
require 'nokogiri'
require 'will_paginate/array'

class PlayersController < ApplicationController
  before_action :set_player, only: %i[show edit update destroy]

  def set_default_description
    @default_description = 'F2P.wiki is an open source Old School RuneScape hiscores for Free-to-play players. It also includes EHP tracking, information about meta changes, and various F2P Old School RuneScape tools.'
  end
  before_action :set_default_description

  def search_player_if_needed
    if params[:search]
      name = Player.sanitize_name(params[:search])
      @player = Player.find_player(name)
      if @player
        redirect_to "/players/#{@player.player_name.gsub(" ", "_").encode("ASCII", invalid: :replace, undef: :replace, replace: '_')}"
      else
        redirect_to ranks_path, notice: "Player '#{name}' not found."
      end
      return
    end
  end

  def create_player_if_needed
    if !params[:player_to_add_name].nil? and params[:player_to_add_name] != ""
      if params[:player_to_add_name].length > 12
        redirect_to ranks_path, notice: 'Invalid player name.'
        return
      end

      name = Player.sanitize_name(params[:player_to_add_name])
      params[:player_to_add_name] = nil
      session[:player_to_add_name] = nil

      result = Player.create_new(name)

      case result
      when nil
        redirect_to ranks_path, notice: "Player hiscores not found."
      when 'exists'
        redirect_to "/players/#{name.gsub(" ", "_")}", notice: "The player you wish to add already exists."
      when 'p2p'
        redirect_to ranks_path, notice: "The player you wish to add is not a free to play account."
      when 'cutoff'
        redirect_to ranks_path, notice: "The player you wish to add does not meet the EHP requirement."
      when 'failed'
        redirect_to ranks_path, notice: 'Unable to fetch player hiscores.'
      else
        redirect_to result, notice: "Player added successfully."
      end
    end
  end

  def tracking
    search_player_if_needed
    create_player_if_needed

    @sort_by = params[:sort_by] || session[:sort_by] || {}
    @filters = params[:filters_] || session[:filters_] || {}
    @restrictions = params[:restrictions] || {}
    @skill = params[:skill] || session[:skill] || {}
    unless F2POSRSRanks::Application.config.f2p_skills.include?(@skill)
      @skill = "overall"
      params[:skill] = "overall"
      session[:skill] = "overall"
    end
    @show_limit = params[:show_limit] || session[:show_limit] || 100
    @show_limit = [@show_limit.to_i, 500].min
    @time = params[:time] || session[:time] || "week"
    @clear_filters = params[:clear_filters]
    @clan_filters = params[:clans_] || session[:clans_] || {}

    if @clear_filters
      @sort_by = {}
      @filters = {}
      @restrictions = {}
      @skill = {}
      @show_limit = 100
      @clan_filters = {}
    end

    case @time
    when "day"
      @time_display = Time.now.gmtime.strftime("%b %d, %Y")
    when "week"
      @time_display = Time.now.gmtime.beginning_of_week.strftime("%b %d, %Y")
    when "month"
      @time_display = Time.now.gmtime.strftime("%b %Y")
    when "year"
      @time_display = Time.now.gmtime.year
    end

    if @filters == {}
      @filters = {"Reg": 1, "IM": 1, "UIM": 1, "HCIM": 1}
      params[:filters_] = @filters
      session[:filters_] = @filters
    end

    if @clan_filters == {}
      @clan_filters = Clan.all.map{ |c| {"#{c.name}": 1} }.reduce(:merge)
      @clan_filters["None"] = 1
      params[:clans_] = @clan_filters
      session[:clans_] = @clan_filters
    end

    if @skill == "combat"
      @skill = "overall"
      params[:skill] = "overall"
      session[:skill] = "overall"
    end

    if @sort_by == "lvl"
      @sort_by = "ehp"
      params[:sort_by] = "ehp"
      session[:sort_by] = "ehp"
    end

    if params[:player1] and params[:player2]
      compare
    end

    if @skill == {}
      @skill = "overall"
      params[:skill] = "overall"
      session[:skill] = "overall"
    end

    if @sort_by == {}
      @sort_by = "ehp"
    end

    if params[:filters_] != session[:filters_] || params[:sort_by] != session[:sort_by] || params[:skill] != session[:skill] || params[:show_limit] != session[:show_limit] || params[:restrictions] != session[:restrictions] || params[:time] != session[:time] || params[:clans_] != session[:clans_]
      session[:filters_] = @filters
      session[:restrictions] = @restrictions
      session[:skill] = @skill
      session[:sort_by] = @sort_by
      session[:show_limit] = @show_limit
      session[:time] = @time
      session[:clans_] = @clan_filters
    end

    case @sort_by
    when "ehp"
      @player_ehp_header = 'hilite'
      ordering = "#{@skill}_ehp - #{@skill}_ehp_#{@time}_start DESC, #{@skill}_xp - #{@skill}_xp_#{@time}_start DESC, #{@skill}_ehp DESC, #{@skill}_xp DESC, players.id ASC"
    when "xp"
      @player_xp_header = 'hilite'
      ordering = "#{@skill}_xp - #{@skill}_xp_#{@time}_start DESC, #{@skill}_ehp - #{@skill}_ehp_#{@time}_start DESC, #{@skill}_xp DESC"
    end

    @players = Player.limit(@show_limit.to_i).where("overall_ehp > 250 OR player_name IN #{Player.sql_supporters}").where(player_acc_type: @filters.keys).where("overall_ehp_day_start > 0").order(Arel.sql(ordering))

    if @restrictions["10 hitpoints"]
      @players = @players.where(hitpoints_lvl: 10).where("combat_lvl >= 4")
    end
    if @restrictions["1 defence"]
      @players = @players.where(defence_lvl: 1).where("combat_lvl >= 4")
    end
    if @restrictions["3 combat"]
      @players = @players.where("combat_lvl < 4").where("overall_lvl <= 816")
    end
    if @restrictions["combat only"]
      @players = @players.where(cooking_lvl: 1).where(woodcutting_lvl: 1).where(fishing_lvl: 1).where(firemaking_lvl: 1).where(crafting_lvl: 1).where(smithing_lvl: 1).where(mining_lvl: 1).where(runecraft_lvl: 1).where("combat_lvl > 10")
    end

    clan_filter_clause = @clan_filters.keys
    clan_filter_clause += [nil] if @clan_filters["None"]


    # clan filter breaks page for some reason
    #@players = @players.left_joins(:clans).merge(Clan.where(name: clan_filter_clause)).distinct.where("potential_p2p <= 0").where("overall_ehp > 1").paginate(:page => params[:page], :per_page => @show_limit.to_i)
    @players = @players.where("potential_p2p <= 0").where("overall_ehp > 1").paginate(:page => params[:page], :per_page => @show_limit.to_i)
  end

  def records
    search_player_if_needed
    create_player_if_needed

    Time.zone = "Pacific Time (US & Canada)"
    @sort_by = params[:sort_by] || session[:sort_by] || {}
    @filters = params[:filters_] || session[:filters_] || {}
    @restrictions = params[:restrictions] || {}
    @skill = params[:skill] || session[:skill] || {}
    unless F2POSRSRanks::Application.config.f2p_skills.include?(@skill)
      @skill = "overall"
      params[:skill] = "overall"
      session[:skill] = "overall"
    end
    @show_limit = params[:show_limit] || session[:show_limit] || 100
    @show_limit = [@show_limit.to_i, 500].min
    @time = params[:time] || session[:time] || "week"

    @clear_filters = params[:clear_filters]
    @clan_filters = params[:clans_] || session[:clans_] || {}

    if @clear_filters
      @sort_by = {}
      @filters = {}
      @restrictions = {}
      @skill = {}
      @show_limit = 100
      @clan_filters = {}
    end

    case @time
    when "day"
      @time_display = Time.zone.now.strftime("%b %d, %Y")
    when "week"
      @time_display = Time.zone.now.beginning_of_week.strftime("%b %d, %Y")
    when "month"
      @time_display = Time.zone.now.strftime("%b %Y")
    when "year"
      @time_display = Time.zone.now.year
    end

    if @filters == {}
      @filters = {"Reg": 1, "IM": 1, "UIM": 1, "HCIM": 1}
      params[:filters_] = @filters
      session[:filters_] = @filters
    end

    if @clan_filters == {}
      @clan_filters = Clan.all.map{ |c| {"#{c.name}": 1} }.reduce(:merge)
      @clan_filters["None"] = 1
      params[:clans_] = @clan_filters
      session[:clans_] = @clan_filters
    end

    if @skill == "combat"
      @skill = "overall"
      params[:skill] = "overall"
      session[:skill] = "overall"
    end

    if @sort_by == "lvl"
      @sort_by = "ehp"
      params[:sort_by] = "ehp"
      session[:sort_by] = "ehp"
    end

    if params[:player1] and params[:player2]
      compare
    end

    if @skill == {}
      @skill = "overall"
      params[:skill] = "overall"
      session[:skill] = "overall"
    end

    if @sort_by == {}
      @sort_by = "ehp"
    end

    if params[:filters_] != session[:filters_] || params[:sort_by] != session[:sort_by] || params[:skill] != session[:skill] || params[:show_limit] != session[:show_limit] || params[:restrictions] != session[:restrictions] || params[:time] != session[:time] || params[:clans_] != session[:clans_]
      session[:filters_] = @filters
      session[:restrictions] = @restrictions
      session[:skill] = @skill
      session[:sort_by] = @sort_by
      session[:show_limit] = @show_limit
      session[:time] = @time
      session[:clans_] = @clan_filters
    end

    case @sort_by
    when "ehp"
      @player_ehp_header = 'hilite'
      ordering = "#{@skill}_ehp_#{@time}_max DESC, #{@skill}_xp_#{@time}_max DESC, #{@skill}_ehp DESC, #{@skill}_xp DESC, players.id ASC"
    when "xp"
      @player_xp_header = 'hilite'
      ordering = "#{@skill}_xp_#{@time}_max DESC, #{@skill}_ehp_#{@time}_max DESC, #{@skill}_xp DESC"
    end

    clan_filter_clause = @clan_filters.keys
    clan_filter_clause += [nil] if @clan_filters["None"]

    @players = Player.limit(@show_limit.to_i).left_joins(:clans).merge(Clan.where(name: clan_filter_clause)).distinct.where("overall_ehp > 250 OR player_name IN #{Player.sql_supporters}").where(player_acc_type: @filters.keys).where("overall_ehp_day_max > 0").order(Arel.sql(ordering))

    if @restrictions["10 hitpoints"]

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/controls.html.haml
- @title = "Admin Page" 
= link_to image_tag("f2pwiki.png"), players_path

= render :partial => "header.html.haml",  :locals => {notice: notice}

= content_tag(:div, nil, style: " margin: auto; text-align: center; width: 155px; padding: 10px;") do 
  = link_to "View Plaintext Player List", plaintext_path
%br
%br

= button_to "Update Items", {:method => "put", :controller => "items", :action => "update_prices"} 
%br
%br

app/views/players/plaintext.html.haml
%p#notice= notice

- skill_list = F2POSRSRanks::Application.config.f2p_skills.clone
- skill_list << "overall"
= skill_list
- Player.all.order("overall_ehp DESC").each do |player|
  - if not player.player_name.nil?
    - name = player.player_name.gsub(" ", "_")
  - else
    - name = player.player_name
  - str = "              { 'player_name': '#{player.player_name}', 'player_acc_type': '#{player.player_acc_type}'"
  - skill_list.each do |skill|
    - lvl = "#{skill}_lvl"
    - xp = "#{skill}_xp"
    - ehp = "#{skill}_ehp"
    - if (not player["#{lvl}"].nil?) and player['potential_p2p'] == '0'
      - str = str + ", #{skill}_lvl: #{player[lvl]}"
    - else
      - str = str +  ", #{skill}_lvl: 0"
    - if (not player["#{xp}"].nil?) and player['potential_p2p'] == '0'
      - str = str +  ", #{skill}_xp: #{player[xp]}"
    - else
      - str = str +  ", #{skill}_xp: 0"
    - if (not player["#{ehp}"].nil?) and player['potential_p2p'] == '0'
      - str = str +  ", #{skill}_ehp: #{player[ehp]}"
    - else
      - str = str +  ", #{skill}_ehp: 0"
  - str = str + ", overall_ehp_start: #{player.overall_ehp_start || 0}"
  - str = str + ", overall_ehp_end: #{player.overall_ehp_end || 0}"
  - str = str +  "},\n"
  = str
  %br

app/views/players/records.html.haml
- @title = "Record Gains" 
- @description = "F2P account XP and EHP records set for Day, Week, Month and Year." 
= link_to image_tag("f2pwiki.png"), players_path

= render :partial => "header.html.haml",  :locals => {notice: notice}

- skill_name = "#{@skill}".capitalize
= content_tag(:div, nil, class: "container", style: "width: 800px;") do 
  = content_tag(:div, nil, class: ["container", "left"], style: "margin-left: 0px; margin-right: 5px; width: 200px;") do 
    = content_tag(:div, nil, class: "container", id: "headerSkills", style: "margin: auto; margin-bottom: 0px; width: 200px; height: 103px;") 
    = content_tag(:div, nil, class: ["container", "skills"], style: "width: 200px; margin-bottom: 0px; line-height: 28px;") do
      = content_tag(:div, nil, class: ["container"], style: "margin-left: 43px; margin-bottom: 0px;") do
        %table{class: "no-format"}
          %tbody
            %tr
              %td{:align => "center"}= image_tag "skills/overall.png", style: "vertical-align: -6px;"
              %td= link_to "Overall", :controller => "players", :action => "records", :skill => "overall"
            - F2POSRSRanks::Application.config.f2p_skills.each do |skill|
              %tr
                %td{:align => "center"}= image_tag "skills/#{skill}.png", style: "vertical-align: -6px;"
                %td= link_to "#{skill.capitalize}", :controller => "players", :action => "records", :skill => "#{skill}"
        
    = content_tag(:div, nil, class: "container", id: "footerSkills", style: "margin: auto; margin-top: 0px; width: 200px; height: 60px;") 

  = content_tag(:div, nil, class: ["container", "left"], style: "width: 430px; max-width: 430px; overflow-x: auto; margin-top: 5px;") do 
    = content_tag(:div, nil, class: "container", id: "headerHiscores", style: "margin: auto; margin-bottom: 0px; width: 430px; height: 41px;") 
    = content_tag(:table, nil, style: "text-align: center; width: 430px; padding: 4px; margin-bottom: 0px;") do 
      %thead
        %tr
          %th{:align => "center", :colspan => 6}
            = image_tag "skills/#{@skill}.png", style: "vertical-align: -6px;"
            = "F2P #{skill_name} #{@sort_by.upcase}: Record #{@time.capitalize}"
      %thead
        %tr
          %th Rank
          %th{:align => "left"} Name
          %th Account
          - if @sort_by == "xp"
            %th{:class => @player_xp_header, :style => "text-decoration: underline;"}= link_to "Record XP", records_path(:sort_by => 'xp', :skill => @skill), :id => 'player_xp_header'
          - else
            %th{:class => @player_xp_header}= link_to "Record XP", records_path(:sort_by => 'xp', :skill => @skill), :id => 'player_xp_header'
          - if @sort_by == "ehp"
            %th{:class => @player_ehp_header, :style => "text-decoration: underline;"}= link_to "Record EHP", records_path(:sort_by => 'ehp', :skill => @skill), :id => 'player_ehp_header'
          - else
            %th{:class => @player_ehp_header}= link_to "Record EHP", records_path(:sort_by => 'ehp', :skill => @skill), :id => 'player_ehp_header'
  
      %tbody
        - @players.each.with_index 1 do |player, index|
          %tr
            - offset = index + (@players.current_page - 1)*@show_limit.to_i
            %td{:align => "right"}= offset
            - name = player.player_name.gsub(" ", "_")
            %td{:align => "left"}= link_to player.player_name, "players/#{name}"
            %td{:align => "center"}= player.player_acc_type
            %td= number_with_delimiter(player["#{@skill}_xp_#{@time}_max"].to_i, :delimiter => ",") 
            %td= number_with_delimiter(number_with_precision(player["#{@skill}_ehp_#{@time}_max"].to_f, precision: 2), :delimiter => ",", :separator => ".") 
            
    = content_tag(:div, nil, class: "container", id: "footerHiscores", style: "margin: auto; margin-top: 0px; width: 430px; height: 41px;") 

  = content_tag(:div, nil, class: ["container", "left"], style: "width: 160px; max-width: 430px; overflow-x: auto; margin-top: 5px;") do 
    = content_tag(:div, nil, class: ["container", "left", "search"], style: "margin-left: 15px; width: 140px; height: 96px;") do 
      = form_tag records_path, :method => "get", id: "search-players-form" do
        = "Search by name"
        %br
        = text_field_tag :search, params[:search], placeholder: "Player Name", :class => "search-field", style: "width: 100px;"
        %br
        = submit_tag "Search"
        
    = content_tag(:div, nil, class: ["container", "left", "search"], style: "margin-left: 15px; width: 140px; height: 96px;") do 
      = form_tag records_path, :method => "get", id: "add-player-form" do
        = "Add to Hiscores"
        %br
        = text_field_tag :player_to_add_name, params[:player_to_add_name], placeholder: "Player Name", :class => "add-player-field", style: "width: 100px;"
        = submit_tag "Add"
        
    = content_tag(:div, nil, class: ["container", "left", "filter"], style: "margin-left: 15px; width: 140px; height: 126px;") do 
      = form_tag compare_path, :method => :get, :id => 'filters_form' do
        = "Compare Users"
        %br
        = text_field_tag :player1, params[:player1], placeholder: "First Player", :class => "search-field", style: "width: 100px;"
        %br
        = text_field_tag :player2, params[:player2], placeholder: "Second Player", :class => "search-field", style: "width: 100px;"
        %br
        = submit_tag 'Compare', :id => "compare_submit"
  
    = content_tag(:div, nil, class: ["container", "left", "search"], style: "margin-left: 15px; width: 140px; height: 96px;") do 
      = form_tag records_path, :method => :get, :id => 'filters_form' do
        = "Time Period"
        %br
        = content_tag(:div, nil, class: "container", style: "color: #d9c27e; text-align: left; width: 126px; margin-left: 25px;") do
          = link_to "Day", records_path(:time => "day")
          &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          = link_to "Week", records_path(:time => "week")
          %br
          = link_to "Month", records_path(:time => "month")
          &nbsp&nbsp&nbsp
          = link_to "Year", records_path(:time => "year")

    %br
    = link_to "Reset filters", records_path(:clear_filters => "true")
    %br
  
    = content_tag(:div, nil, class: ["container", "left", "filter"], style: "margin-left: 15px; width: 140px; height: 126px;") do 
      = form_tag records_path, :method => :get, :id => 'filters_form' do
        = "Filter Accounts"
        %br
        = content_tag(:div, nil, class: "container", style: "color: #d9c27e; text-align: left; width: 138px; margin-bottom: 0px;") do
          - ["Reg", "IM", "UIM", "HCIM"].each do |type|
            &nbsp
            = check_box_tag "filters_[#{type}]", 1, @filters.include?(type), :id => "filters_#{type}"
            = type
            - if type == "IM"
              %br
        = submit_tag 'Filter', :id => "filters_submit"
        
    = content_tag(:div, nil, class: ["container", "left", "filter"], style: "line-height: 18px; margin-left: 15px; width: 140px; height: 126px;") do 
      = form_tag records_path, :method => :get, :id => 'restrictions_form' do
        = "Restrictions"
        %br
        = content_tag(:div, nil, class: "container", style: "color: #d9c27e; text-align: left; width: 126px; margin-bottom: 0px;") do
          - ["3 combat", "1 defence", "10 hitpoints", "combat only"].each do |type|
            &nbsp
            = radio_button_tag "restrictions", type, @restrictions.include?(type), :id => "restrictions_#{type}"
            = type
            %br
        = submit_tag 'Filter', :id => "restrictions_submit"
  
    %br
    - container_height = 126 + (18 * [Clan.all.count - 2, 0].max)
    = content_tag(:div, nil, class: ["container", "left", "filter"], style: "line-height: 18px; margin-left: 15px; width: 140px; height: #{container_height}px; background-size: 100% 100%;") do
      = form_tag records_path, :method => :get, :id => 'clans_form' do
        = "Clans"
        %br
        = content_tag(:div, nil, class: "container", style: "color: #d9c27e; text-align: left; width: 126px; margin-bottom: 0px;") do
          - Clan.all.each do |clan|
            &nbsp
            = check_box_tag "clans_[#{clan.name}]", 1, @clan_filters.include?(clan.name), :id => "clans_#{clan.name}"
            = clan.name
            %br
          &nbsp
          = check_box_tag "clans_[None]", 1, @clan_filters.include?("None"), :id => "clans_None"
          = "None"
        = submit_tag 'Filter', :id => "clans_submit"

    = content_tag(:div, nil, class: ["container", "left", "search"], style: "margin-left: 15px; width: 140px; height: 96px;") do 
      = form_tag records_path, :method => :get, :id => 'show_limits_form' do
        = "Players Per Page"
        %br
        = select_tag :show_limit, options_for_select(["25", "50", "100", "250", "500"], @show_limit)
        %br
        = submit_tag 'Refresh', :id => "show_limit_submit"

= will_paginate @players

app/views/players/secretpage.html.haml
= content_tag(:div, nil, class: ["div", "title"]) do 
  %h1 
    = link_to "F2P.wiki", players_path
  = content_tag(:div, nil, class: ["container", "subtitle"]) do 
    = "for all your F2P OSRS needs"
  %p#notice= notice

%br
= content_tag(:div, nil, class: "container", style: "width: 820px;") do 
  = content_tag(:div, nil, class: ["bar", "ranks"]) do
    = link_to "F2P OSRS Ranks", ranks_path
  = content_tag(:div, nil, class: ["bar", "ehp"]) do 
    = link_to "EHP Rates", ehp_path
  = content_tag(:div, nil, class: ["bar", "fake"]) do 
    = link_to "Hall of Shame", fake_path
  = content_tag(:div, nil, class: ["bar", "links"]) do 
    = link_to "Useful Links", links_path
  = content_tag(:div, nil, class: ["bar", "changelog"]) do 
    = link_to "Changelog", changelog_path
  = content_tag(:div, nil, class: ["bar", "donate"]) do 
    = link_to "About Us/Donations", donate_path

= content_tag(:div, nil, style: " margin: auto; text-align: center; width: 155px; padding: 10px;") do 
  = link_to "View Plaintext Player List", plaintext_path
%br
%br
= button_to "Update All Players\' Stats", {:method => "put", :controller => "players", :action => "refresh_players"} 
%br
%br
= button_to "Update Top 250 Players\' Stats", {:method => "put", :controller => "players", :action => "refresh_250"} 
%br
%br
= button_to "Export All Players\' Stats", {:controller => "players", :action => "export_players"} 
%br
%br
= form_tag ranks_path, :method => "get", id: "create-player-form" do
  = "Add a missing Player"
  %br
  = text_field_tag :player_to_add_name, params[:player_to_add_name], placeholder: "Player Name"
  = "Player Name"
  %br
  = text_field_tag :player_to_add_acc, params[:player_to_add_acc], placeholder: "Player Account Type"
  = "Player Account Type"
  %br
  = submit_tag "Add" 

%br
%br
= form_tag ranks_path, :method => "get", id: "delete-player-form" do
  = "Remove a Player"
  %br
  = text_field_tag :player_to_del_name, params[:player_to_del_name], placeholder: "Player Name"
  = "Player Name"
  %br
  = submit_tag "Delete" 